In [3]:
# import the pandas library
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(5, 3), index=['a', 'c', 'e', 'f',
'h'],columns=['one', 'two', 'three'])



df = df.reindex(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])

print (df)

        one       two     three
a -0.854946  0.309388 -0.870657
b       NaN       NaN       NaN
c -0.053343  0.848677  0.071907
d       NaN       NaN       NaN
e -0.414085 -0.011873 -0.455281
f -0.819745 -2.343157  0.135045
g       NaN       NaN       NaN
h  0.050102 -2.940973  0.196716


In [7]:
import numpy as np

#a = np.random.randint(-10,7,3)
a = np.random.randn(5,3)

print(a)

[[ 0.01245596  0.00971249  0.55128697]
 [-0.90786176 -0.20392488 -0.31617741]
 [-0.28592567 -0.33677226  1.85224126]
 [-0.52482804 -0.67588183 -0.50691046]
 [ 1.12717922 -0.14436    -0.76281438]]


In [10]:
#print(df.isnull)

df.isnull().values


#df.isnull().sum()


#df.isnull().sum().sum()

array([[False, False, False],
       [ True,  True,  True],
       [False, False, False],
       [ True,  True,  True],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [7]:

print (df.fillna(0))

        one       two     three
a -0.509964  0.182489 -0.638296
b  0.000000  0.000000  0.000000
c -0.899679 -0.058783  0.482970
d  0.000000  0.000000  0.000000
e -0.308811  2.342158  0.407501
f -0.922852  1.410846  0.176285
g  0.000000  0.000000  0.000000
h -1.607570 -1.064794  0.071291


In [ ]:
print (df.fillna(method='pad'))

        one       two     three
a -1.152214 -1.136806 -0.497569
b -1.152214 -1.136806 -0.497569
c -1.281870  0.161174  1.139403
d -1.281870  0.161174  1.139403
e -0.147394 -0.080536 -0.901719
f -1.121914 -0.722028  0.329840
g -1.121914 -0.722028  0.329840
h -0.247669 -0.791820  1.169386


Data filling techniques 
https://towardsdatascience.com/how-to-fill-missing-data-with-pandas-8cb875362a0d

In [ ]:
df = pd.DataFrame({'date':['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04','2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04'], 'fruit':['apple', 'apple', 'apple', 'apple', 'mango', 'mango', 'mango', 'mango'], 'price': [0.80, None, None, 1.20, None, 2.10, 2.00, 1.80]})
df['date'] = pd.to_datetime(df['date'])
print(df)

        date  fruit  price
0 2021-01-01  apple    0.8
1 2021-01-02  apple    NaN
2 2021-01-03  apple    NaN
3 2021-01-04  apple    1.2
4 2021-01-01  mango    NaN
5 2021-01-02  mango    2.1
6 2021-01-03  mango    2.0
7 2021-01-04  mango    1.8


Fill with Constant Value

In [ ]:
df['price'].fillna(value = 0.85, inplace = True)
print(df)

        date  fruit  price
0 2021-01-01  apple   0.80
1 2021-01-02  apple   0.85
2 2021-01-03  apple   0.85
3 2021-01-04  apple   1.20
4 2021-01-01  mango   0.85
5 2021-01-02  mango   2.10
6 2021-01-03  mango   2.00
7 2021-01-04  mango   1.80


Fill with Mean / Median of Column

In [ ]:
# mean
df['price'].fillna(value = df.price.mean(), inplace = True)
print(df)

In [ ]:
# median
df['price'].fillna(value = df.price.median(), inplace = True)
print(df)

Fill with Mean / Median of Group

In [ ]:
# mean
df['price'].fillna(df.groupby('fruit')['price'].transform('mean'), inplace = True)
print(df)
# median
df['price'].fillna(df.groupby('fruit')['price'].transform('median'), inplace = True)
print(df)

Forward Fill

In [ ]:
df['price'].fillna(method = 'ffill', inplace = True)

the data science and prcoessing  
https://www.w3schools.com/python/python_ml_mean_median_mode.asp

Reading CSV and the functioanlity 

In [ ]:
import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/diabetes.csv')
print (data)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                  

In [ ]:

# Slice the result for first 5 rows
print (data[0:5]['Glucose'])

0    148
1     85
2    183
3     89
4    137
Name: Glucose, dtype: int64


In [ ]:
# Use the multi-axes indexing funtion
print (data.loc[:,['Glucose','BloodPressure']])

In [ ]:
# Use the multi-axes indexing funtion
print (data.loc[[1,3,5],['Glucose','BloodPressure']])

   Glucose  BloodPressure
1       85             66
3       89             66
5      116             74


In [ ]:
# Use the multi-axes indexing funtion
print (data.loc[2:6,['Glucose','BloodPressure']])

   Glucose  BloodPressure
2      183             64
3       89             66
4      137             40
5      116             74
6       78             50
